### PR TITLE
Create logo

### LINKED ISSUE #1: Create Logo
We need a logo to add to our docs and README pages

### PR DESCRIPTION
**Pull request by LyubomirT**
## Summary

This Pull Request adds a logo and a banner to the application, though still in progress (related to #1).

## Checklist

- [ ] If code changes were made then they have been tested on a real VEX Brain.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue (state the issue in the summary).
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by TheMaster3558 — COMMENTED** [review]
Could you add a version with a transparent background. That would work better on the docs website.

**Comment by LyubomirT** [comment]
Sure thing! Getting started on that right away.

**Comment by TheMaster3558** [comment]
Looks good! Would you think the logo with text would work better on the top bar of the [docs](https://https://themaster3558.github.io/Master-Selector/) or would the logo with only the symbol look better?

**Comment by LyubomirT** [comment]
> Looks good! Would you think the logo with text would work better on the top bar of the [docs](https://https://themaster3558.github.io/Master-Selector/) or would the logo with only the symbol look better?

It's totally up to you, but I believe that the logo will look better as a symbol along with the text on the top bar. But as I said, you make the final call. :)

**Comment by TheMaster3558** [comment]
Could you make a version of the logo that has text but with no background? (You made a no background version of the symbol only logo but the symbol + text logo would work better with no background on the website). Also, if it's possible, it would be preferred to have the logos in SVG format rather than PNG format (but if not it's fine).

**Comment by LyubomirT** [comment]
Alright! I'll try to make it an SVG, but note that the base image of the logo has been Photoshopped to PNG and most likely will have scaling issues. But the text should work well.

**Comment by LyubomirT** [comment]
It might take a little while though, I'll have to go through some medication today.

**Comment by LyubomirT** [comment]
@TheMaster3558 Just for clarification: Do you have any particular font/resolution preferences for the logo?

**Comment by TheMaster3558** [comment]
I think the current font looks good. I hope you recover well from your sickness!

**Comment by LyubomirT** [comment]
Master-Selector

Done with the .svg version of the logo, figured out your documentation website uses Inter so the same font is utilized :)

I attempted to remove the background of the logo, so when previewing it you'll probably see pure whiteness. Considering that the logo is a .png injected into an .svg, I'd better create a lightmode version as well, will push the changes when I'm done.

**Comment by LyubomirT** [comment]
Master-Selector (2)

**Comment by TheMaster3558** [comment]
Looks Great! I'll add some commits to this PR to integrate it to sphinx

**Comment by LyubomirT** [comment]
Roger that, good luck with integrating it into Sphinx :)

**Comment by TheMaster3558** [comment]
Hi, where would you want credits for your logo to be in this project? I was thinking maybe the docs footer and below the logo in the README

**Comment by LyubomirT** [comment]
> Hi, where would you want credits for your logo to be in this project? I was thinking maybe the docs footer and below the logo in the README

Anywhere you'd like, but I don't think that a credit is necessary, I'm just happy to help however I can!

**Comment by TheMaster3558** [comment]
Merged. Looks great!

**Pull request merged**
